name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./

      - run: nu ./tests/script.nu
